import { describe, it, afterEach } from 'node:test'
import assert from 'node:assert/strict'
import { writeFileSync, mkdirSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { getAllInstalledDeps, getAllInstalledVersions } from '../src/lockfile.js'

const tmpDir = join(import.meta.dirname, '.tmp-lockfile-test')

function setup() {
  mkdirSync(tmpDir, { recursive: true })
}

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true })
})

// ─── yarn.lock classic (v1) ─────────────────────────────────────────────────

describe('yarn.lock classic', () => {
  it('extracts dependency names', () => {
    setup()
    writeFileSync(join(tmpDir, 'yarn.lock'), `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


accepts@~1.3.8:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz#0bf0"
  integrity sha512-PYA==
  dependencies:
    mime-types "~2.1.34"
    negotiator "0.6.3"

array-flatten@1.1.1:
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/array-flatten/-/array-flatten-1.1.1.tgz#9a5f"
  integrity sha512-PCVAQs==

"@types/node@^20.0.0":
  version "20.19.39"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.19.39.tgz#e98a"
  integrity sha512-orrrD74==
  dependencies:
    undici-types "~6.21.0"

express@^4.18.0:
  version "4.21.2"
  resolved "https://registry.yarnpkg.com/express/-/express-4.21.2.tgz#3c3c"
  integrity sha512-28HqgM==
`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('accepts'))
    assert.ok(deps.has('array-flatten'))
    assert.ok(deps.has('@types/node'))
    assert.ok(deps.has('express'))
    assert.strictEqual(deps.size, 4)
  })

  it('extracts dependency versions', () => {
    setup()
    writeFileSync(join(tmpDir, 'yarn.lock'), `# yarn lockfile v1

accepts@~1.3.8:
  version "1.3.8"
  resolved "https://registry.yarnpkg.com/accepts/-/accepts-1.3.8.tgz"

"@babel/core@^7.12.9":
  version "7.12.9"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.12.9.tgz"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
`)

    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.get('accepts'), '1.3.8')
    assert.strictEqual(versions.get('@babel/core'), '7.12.9')
    assert.strictEqual(versions.get('lodash'), '4.17.21')
    assert.strictEqual(versions.size, 3)
  })

  it('handles multi-range entries', () => {
    setup()
    writeFileSync(join(tmpDir, 'yarn.lock'), `# yarn lockfile v1

"whatwg-mimetype@^2.2.0", "whatwg-mimetype@^2.3.0":
  version "2.3.0"
  resolved "https://registry.yarnpkg.com/whatwg-mimetype/-/whatwg-mimetype-2.3.0.tgz"
`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('whatwg-mimetype'))
    assert.strictEqual(deps.size, 1)

    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.get('whatwg-mimetype'), '2.3.0')
  })

  it('returns empty set for empty yarn.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'yarn.lock'), '# yarn lockfile v1\n')

    const deps = getAllInstalledDeps(tmpDir)
    assert.strictEqual(deps.size, 0)
  })

  it('returns empty set for malformed yarn.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'yarn.lock'), 'this is not a valid lockfile\n{{{')

    const deps = getAllInstalledDeps(tmpDir)
    assert.strictEqual(deps.size, 0)
  })
})

// ─── bun.lock ────────────────────────────────────────────────────────────────

describe('bun.lock', () => {
  it('extracts dependency names', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), JSON.stringify({
      lockfileVersion: 0,
      workspaces: {
        '': { dependencies: { express: '^4.21.1', lodash: '^4.17.21' } },
      },
      packages: {
        'express': ['express@4.21.2', '', {}, 'sha512-abc=='],
        'lodash': ['lodash@4.17.21', '', {}, 'sha512-def=='],
        '@types/node': ['@types/node@25.0.0', '', { dependencies: { 'undici-types': '~7.16.0' } }, 'sha512-ghi=='],
        'accepts': ['accepts@1.3.8', '', {}, 'sha512-jkl=='],
      },
    }))

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('express'))
    assert.ok(deps.has('lodash'))
    assert.ok(deps.has('@types/node'))
    assert.ok(deps.has('accepts'))
    assert.strictEqual(deps.size, 4)
  })

  it('extracts dependency versions', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), JSON.stringify({
      lockfileVersion: 0,
      workspaces: {},
      packages: {
        'express': ['express@4.21.2', '', {}, 'sha512-abc=='],
        '@types/node': ['@types/node@25.0.0', '', {}, 'sha512-def=='],
        'lodash': ['lodash@4.17.21', '', {}, 'sha512-ghi=='],
      },
    }))

    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.get('express'), '4.21.2')
    assert.strictEqual(versions.get('@types/node'), '25.0.0')
    assert.strictEqual(versions.get('lodash'), '4.17.21')
    assert.strictEqual(versions.size, 3)
  })

  it('handles JSONC with trailing commas', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), `{
  "lockfileVersion": 0,
  "workspaces": {
    "": {
      "dependencies": {
        "express": "^4.21.1",
      },
    },
  },
  "packages": {
    "express": ["express@4.21.2", "", {}, "sha512-abc=="],
    "accepts": ["accepts@1.3.8", "", {}, "sha512-def=="],
  },
}`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('express'))
    assert.ok(deps.has('accepts'))
    assert.strictEqual(deps.size, 2)
  })

  it('handles JSONC with comments', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), `{
  // This is a comment
  "lockfileVersion": 0,
  "workspaces": {},
  /* Block comment */
  "packages": {
    "express": ["express@4.21.2", "", {}, "sha512-abc=="],
  },
}`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('express'))
    assert.strictEqual(deps.size, 1)
  })

  it('skips workspace and github specs in version extraction', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), JSON.stringify({
      lockfileVersion: 0,
      workspaces: {},
      packages: {
        '@types/bun': ['@types/bun@workspace:packages/@types/bun'],
        'bun-tracestrings': ['bun-tracestrings@github:oven-sh/bun.report#912ca63', {}],
        'express': ['express@4.21.2', '', {}, 'sha512-abc=='],
      },
    }))

    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.has('@types/bun'), false)
    assert.strictEqual(versions.has('bun-tracestrings'), false)
    assert.strictEqual(versions.get('express'), '4.21.2')
    assert.strictEqual(versions.size, 1)

    // But names should still be extracted
    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('@types/bun'))
    assert.ok(deps.has('bun-tracestrings'))
    assert.ok(deps.has('express'))
    assert.strictEqual(deps.size, 3)
  })

  it('returns empty set for empty bun.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), '{}')

    const deps = getAllInstalledDeps(tmpDir)
    assert.strictEqual(deps.size, 0)
  })

  it('returns empty set for malformed bun.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), 'not json at all {{{')

    const deps = getAllInstalledDeps(tmpDir)
    assert.strictEqual(deps.size, 0)
  })

  it('handles JSONC with escaped backslashes in strings', () => {
    setup()
    // The value "C:\\Users\\test" contains escaped backslashes followed by quotes
    writeFileSync(join(tmpDir, 'bun.lock'), `{
  "lockfileVersion": 0,
  "workspaces": {},
  "packages": {
    "pkg-with-path": ["pkg-with-path@1.0.0", "C:\\\\Users\\\\test", {}, "sha512-abc=="],
  },
}`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('pkg-with-path'))
    assert.strictEqual(deps.size, 1)

    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.get('pkg-with-path'), '1.0.0')
  })

  it('handles JSONC with unclosed block comment gracefully', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), `{
  "lockfileVersion": 0,
  "packages": {
    "express": ["express@4.21.2", "", {}, "sha=="]
  }
/* unclosed comment`)

    // Should not crash — graceful degradation
    const deps = getAllInstalledDeps(tmpDir)
    // May or may not parse depending on JSON validity after stripping, but must not throw
    assert.ok(deps.size >= 0)
  })

  it('extracts scoped packages correctly', () => {
    setup()
    writeFileSync(join(tmpDir, 'bun.lock'), JSON.stringify({
      lockfileVersion: 0,
      workspaces: {},
      packages: {
        '@babel/core': ['@babel/core@7.26.0', '', { dependencies: { '@babel/generator': '^7.12.5' } }, 'sha512-abc=='],
        '@types/express': ['@types/express@4.17.21', '', {}, 'sha512-def=='],
        'lodash': ['lodash@4.17.21', '', {}, 'sha512-ghi=='],
      },
    }))

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('@babel/core'))
    assert.ok(deps.has('@types/express'))
    assert.ok(deps.has('lodash'))
    assert.strictEqual(deps.size, 3)

    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.get('@babel/core'), '7.26.0')
    assert.strictEqual(versions.get('@types/express'), '4.17.21')
    assert.strictEqual(versions.get('lodash'), '4.17.21')
  })
})

// ─── Lock file priority ──────────────────────────────────────────────────────

describe('lock file priority', () => {
  it('prefers package-lock.json over yarn.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'package-lock.json'), JSON.stringify({
      lockfileVersion: 3,
      packages: { 'node_modules/from-npm': { version: '1.0.0' } },
    }))
    writeFileSync(join(tmpDir, 'yarn.lock'), `# yarn lockfile v1

from-yarn@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/from-yarn/-/from-yarn-1.0.0.tgz"
`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('from-npm'))
    assert.ok(!deps.has('from-yarn'))
  })

  it('prefers pnpm-lock.yaml over yarn.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'pnpm-lock.yaml'), `lockfileVersion: '6.0'\npackages:\n  'from-pnpm@1.0.0':\n    resolution: {integrity: sha512-abc}\n`)
    writeFileSync(join(tmpDir, 'yarn.lock'), `# yarn lockfile v1\n\nfrom-yarn@^1.0.0:\n  version "1.0.0"\n  resolved "https://registry.yarnpkg.com/from-yarn/-/from-yarn-1.0.0.tgz"\n`)

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('from-pnpm'))
    assert.ok(!deps.has('from-yarn'))
  })

  it('prefers yarn.lock over bun.lock', () => {
    setup()
    writeFileSync(join(tmpDir, 'yarn.lock'), `# yarn lockfile v1

from-yarn@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/from-yarn/-/from-yarn-1.0.0.tgz"
`)
    writeFileSync(join(tmpDir, 'bun.lock'), JSON.stringify({
      lockfileVersion: 0,
      workspaces: {},
      packages: { 'from-bun': ['from-bun@1.0.0', '', {}, 'sha512=='] },
    }))

    const deps = getAllInstalledDeps(tmpDir)
    assert.ok(deps.has('from-yarn'))
    assert.ok(!deps.has('from-bun'))
  })

  it('returns empty when no lock file exists', () => {
    setup()
    const deps = getAllInstalledDeps(tmpDir)
    assert.strictEqual(deps.size, 0)
    const versions = getAllInstalledVersions(tmpDir)
    assert.strictEqual(versions.size, 0)
  })
})
